### ISSUE TITLE
install failing on centos 6.7 during execute make install

### ISSUE THREAD

**Issue by nrw** [kafecho/ansible-couchdb2#3]
the error is at the bottom of this issue. if i rerun the playbook, it finishes without errors, but couchdb is not completely installed. for example, if the instance runs, it doesn't have fauxton.

any ideas on how to fix it?

---

TASK [couchdb2 : execute make install] *****************************************
fatal: [ip.removed.for.github.issue]: FAILED! => {"changed": true, "cmd": "make install", "delta": "0:00:02.897168", "end": "2016-04-17 11:53:26.118464", "failed": true, "rc": 2, "start": "2016-04-17 11:53:23.221296", "stderr": "ERROR: compile failed while processing /tmp/couchdb/src/cassim: rebar_abort\nmake: **\* [couch] Error 1", "stdout": "WARN:  Directory expected to be an app dir, but no app file found \nin ebin/ or src/:\n/tmp/couchdb/src/chttpd\nWARN:  Expected /tmp/couchdb/src/docs to be a raw dependency directory, but no directory found.\nWARN:  Expected /tmp/couchdb/src/fauxton to be a raw dependency directory, but no directory found.\n==> couch_epi (compile)\n==> config (compile)\n==> b64url (compile)\n==> cassim (compile)\nCompiled src/cassim_app.erl\n/tmp/couchdb/src/cassim/src/cassim.erl:46: can't find include lib \"couch/include/couch_db.hrl\"\n/tmp/couchdb/src/cassim/src/cassim.erl:61: record httpd undefined\n/tmp/couchdb/src/cassim/src/cassim.erl:65: record httpd undefined\n/tmp/couchdb/src/cassim/src/cassim.erl:66: variable 'Roles' is unbound\n/tmp/couchdb/src/cassim/src/cassim.erl:69: record httpd undefined\n/tmp/couchdb/src/cassim/src/cassim.erl:76: record user_ctx undefined\n/tmp/couchdb/src/cassim/src/cassim.erl:77: variable 'Roles' is unbound\nCompiling /tmp/couchdb/src/cassim/src/cassim.erl failed:", "stdout_lines": ["WARN:  Directory expected to be an app dir, but no app file found ", "in ebin/ or src/:", "/tmp/couchdb/src/chttpd", "WARN:  Expected /tmp/couchdb/src/docs to be a raw dependency directory, but no directory found.", "WARN:  Expected /tmp/couchdb/src/fauxton to be a raw dependency directory, but no directory found.", "==> couch_epi (compile)", "==> config (compile)", "==> b64url (compile)", "==> cassim (compile)", "Compiled src/cassim_app.erl", "/tmp/couchdb/src/cassim/src/cassim.erl:46: can't find include lib \"couch/include/couch_db.hrl\"", "/tmp/couchdb/src/cassim/src/cassim.erl:61: record httpd undefined", "/tmp/couchdb/src/cassim/src/cassim.erl:65: record httpd undefined", "/tmp/couchdb/src/cassim/src/cassim.erl:66: variable 'Roles' is unbound", "/tmp/couchdb/src/cassim/src/cassim.erl:69: record httpd undefined", "/tmp/couchdb/src/cassim/src/cassim.erl:76: record user_ctx undefined", "/tmp/couchdb/src/cassim/src/cassim.erl:77: variable 'Roles' is unbound", "Compiling /tmp/couchdb/src/cassim/src/cassim.erl failed:"], "warnings": []}

**Comment by kafecho** [comment]
Hi, 
I am not 100% sure what is going on here. I've modified the Ansible role to let you pick a given CouchDB git version (via the git_version variable). I can build earlier versions of CouchDB from January 2016, but I cannot build more recent versions. For me, the playbook does not report any error, but I am still unable to load up Fauxton.

**Comment by nrw** [comment]
i've been chatting in #couchdb. apparently this was a problem with fauxton and this issue should be fixed by this commit:

https://github.com/apache/couchdb/commit/5330184cd9405de78e1ba46079ba26098ddcb2f3

i'm trying it now.

**Comment by nrw** [comment]
yep. works with master for me now. if you can confirm, i think this issue is taken care of.

**Comment by kafecho** [comment]
Yes, works for me as well. Thanks for bringing this to my attention.
